import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="base__layout">
          <Sidebar />
          <div className="flex flex-col flex-1 px-9 py-9 p-4">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
